config/routes.rb
Danaciubotaru::Application.routes.draw do
  resources :educations

  resources :companies

  resources :experiences

  resources :cvs

  resources :users

end

app/models/education.rb
class Education < ActiveRecord::Base
  attr_accessible :activities, :degree, :end_time, :name, :start_time
  belongs_to :cv
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @educations }
    end
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
    @education = Education.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/new
  # GET /educations/new.json
  def new
    @education = Education.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/1/edit
  def edit
    @education = Education.find(params[:id])
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(params[:education])

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render json: @education, status: :created, location: @education }
      else
        format.html { render action: "new" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /educations/1
  # PUT /educations/1.json
  def update
    @education = Education.find(params[:id])

    respond_to do |format|
      if @education.update_attributes(params[:education])
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education = Education.find(params[:id])
    @education.destroy

    respond_to do |format|
      format.html { redirect_to educations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<%= form_for(@education) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.date_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.date_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :degree %><br />
    <%= f.text_field :degree %>
  </div>
  <div class="field">
    <%= f.label :activities %><br />
    <%= f.text_area :activities %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
<h1>Listing educations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Degree</th>
    <th>Activities</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @educations.each do |education| %>
  <tr>
    <td><%= education.name %></td>
    <td><%= education.start_time %></td>
    <td><%= education.end_time %></td>
    <td><%= education.degree %></td>
    <td><%= education.activities %></td>
    <td><%= link_to 'Show', education %></td>
    <td><%= link_to 'Edit', edit_education_path(education) %></td>
    <td><%= link_to 'Destroy', education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Education', new_education_path %>

app/views/educations/new.html.erb
<h1>New education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @education.name %>
</p>

<p>
  <b>Start time:</b>
  <%= @education.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @education.end_time %>
</p>

<p>
  <b>Degree:</b>
  <%= @education.degree %>
</p>

<p>
  <b>Activities:</b>
  <%= @education.activities %>
</p>


<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>